// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"

	"entgo.io/bug/ent/unrenameduser"
	"entgo.io/bug/ent/user"
	"entgo.io/contrib/entgql"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Common entgql types.
type (
	Cursor         = entgql.Cursor[int]
	PageInfo       = entgql.PageInfo[int]
	OrderDirection = entgql.OrderDirection
)

func orderFunc(o OrderDirection, field string) func(*sql.Selector) {
	if o == entgql.OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Alias == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// UnrenamedUserEdge is the edge representation of UnrenamedUser.
type UnrenamedUserEdge struct {
	Node   *UnrenamedUser `json:"node"`
	Cursor Cursor         `json:"cursor"`
}

// UnrenamedUserConnection is the connection containing edges to UnrenamedUser.
type UnrenamedUserConnection struct {
	Edges      []*UnrenamedUserEdge `json:"edges"`
	PageInfo   PageInfo             `json:"pageInfo"`
	TotalCount int                  `json:"totalCount"`
}

func (c *UnrenamedUserConnection) build(nodes []*UnrenamedUser, pager *unrenameduserPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *UnrenamedUser
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *UnrenamedUser {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *UnrenamedUser {
			return nodes[i]
		}
	}
	c.Edges = make([]*UnrenamedUserEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &UnrenamedUserEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// UnrenamedUserPaginateOption enables pagination customization.
type UnrenamedUserPaginateOption func(*unrenameduserPager) error

// WithUnrenamedUserOrder configures pagination ordering.
func WithUnrenamedUserOrder(order *UnrenamedUserOrder) UnrenamedUserPaginateOption {
	if order == nil {
		order = DefaultUnrenamedUserOrder
	}
	o := *order
	return func(pager *unrenameduserPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultUnrenamedUserOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithUnrenamedUserFilter configures pagination filter.
func WithUnrenamedUserFilter(filter func(*UnrenamedUserQuery) (*UnrenamedUserQuery, error)) UnrenamedUserPaginateOption {
	return func(pager *unrenameduserPager) error {
		if filter == nil {
			return errors.New("UnrenamedUserQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type unrenameduserPager struct {
	reverse bool
	order   *UnrenamedUserOrder
	filter  func(*UnrenamedUserQuery) (*UnrenamedUserQuery, error)
}

func newUnrenamedUserPager(opts []UnrenamedUserPaginateOption, reverse bool) (*unrenameduserPager, error) {
	pager := &unrenameduserPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultUnrenamedUserOrder
	}
	return pager, nil
}

func (p *unrenameduserPager) applyFilter(query *UnrenamedUserQuery) (*UnrenamedUserQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *unrenameduserPager) toCursor(uu *UnrenamedUser) Cursor {
	return p.order.Field.toCursor(uu)
}

func (p *unrenameduserPager) applyCursors(query *UnrenamedUserQuery, after, before *Cursor) (*UnrenamedUserQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultUnrenamedUserOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *unrenameduserPager) applyOrder(query *UnrenamedUserQuery) *UnrenamedUserQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultUnrenamedUserOrder.Field {
		query = query.Order(DefaultUnrenamedUserOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *unrenameduserPager) orderExpr(query *UnrenamedUserQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultUnrenamedUserOrder.Field {
			b.Comma().Ident(DefaultUnrenamedUserOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to UnrenamedUser.
func (uu *UnrenamedUserQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...UnrenamedUserPaginateOption,
) (*UnrenamedUserConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newUnrenamedUserPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if uu, err = pager.applyFilter(uu); err != nil {
		return nil, err
	}
	conn := &UnrenamedUserConnection{Edges: []*UnrenamedUserEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = uu.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if uu, err = pager.applyCursors(uu, after, before); err != nil {
		return nil, err
	}
	if limit := paginateLimit(first, last); limit != 0 {
		uu.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := uu.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	uu = pager.applyOrder(uu)
	nodes, err := uu.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// UnrenamedUserOrderField defines the ordering field of UnrenamedUser.
type UnrenamedUserOrderField struct {
	// Value extracts the ordering value from the given UnrenamedUser.
	Value    func(*UnrenamedUser) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) unrenameduser.OrderOption
	toCursor func(*UnrenamedUser) Cursor
}

// UnrenamedUserOrder defines the ordering of UnrenamedUser.
type UnrenamedUserOrder struct {
	Direction OrderDirection           `json:"direction"`
	Field     *UnrenamedUserOrderField `json:"field"`
}

// DefaultUnrenamedUserOrder is the default ordering of UnrenamedUser.
var DefaultUnrenamedUserOrder = &UnrenamedUserOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &UnrenamedUserOrderField{
		Value: func(uu *UnrenamedUser) (ent.Value, error) {
			return uu.ID, nil
		},
		column: unrenameduser.FieldID,
		toTerm: unrenameduser.ByID,
		toCursor: func(uu *UnrenamedUser) Cursor {
			return Cursor{ID: uu.ID}
		},
	},
}

// ToEdge converts UnrenamedUser into UnrenamedUserEdge.
func (uu *UnrenamedUser) ToEdge(order *UnrenamedUserOrder) *UnrenamedUserEdge {
	if order == nil {
		order = DefaultUnrenamedUserOrder
	}
	return &UnrenamedUserEdge{
		Node:   uu,
		Cursor: order.Field.toCursor(uu),
	}
}

// RenamedUser is the type alias for User.
type RenamedUser = User

// RenamedUserEdge is the edge representation of RenamedUser.
type RenamedUserEdge struct {
	Node   *RenamedUser `json:"node"`
	Cursor Cursor       `json:"cursor"`
}

// RenamedUserConnection is the connection containing edges to RenamedUser.
type RenamedUserConnection struct {
	Edges      []*RenamedUserEdge `json:"edges"`
	PageInfo   PageInfo           `json:"pageInfo"`
	TotalCount int                `json:"totalCount"`
}

func (c *RenamedUserConnection) build(nodes []*RenamedUser, pager *renameduserPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *RenamedUser
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *RenamedUser {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *RenamedUser {
			return nodes[i]
		}
	}
	c.Edges = make([]*RenamedUserEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &RenamedUserEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// RenamedUserPaginateOption enables pagination customization.
type RenamedUserPaginateOption func(*renameduserPager) error

// WithRenamedUserOrder configures pagination ordering.
func WithRenamedUserOrder(order *RenamedUserOrder) RenamedUserPaginateOption {
	if order == nil {
		order = DefaultRenamedUserOrder
	}
	o := *order
	return func(pager *renameduserPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultRenamedUserOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithRenamedUserFilter configures pagination filter.
func WithRenamedUserFilter(filter func(*UserQuery) (*UserQuery, error)) RenamedUserPaginateOption {
	return func(pager *renameduserPager) error {
		if filter == nil {
			return errors.New("UserQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type renameduserPager struct {
	reverse bool
	order   *RenamedUserOrder
	filter  func(*UserQuery) (*UserQuery, error)
}

func newRenamedUserPager(opts []RenamedUserPaginateOption, reverse bool) (*renameduserPager, error) {
	pager := &renameduserPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultRenamedUserOrder
	}
	return pager, nil
}

func (p *renameduserPager) applyFilter(query *UserQuery) (*UserQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *renameduserPager) toCursor(u *RenamedUser) Cursor {
	return p.order.Field.toCursor(u)
}

func (p *renameduserPager) applyCursors(query *UserQuery, after, before *Cursor) (*UserQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultRenamedUserOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *renameduserPager) applyOrder(query *UserQuery) *UserQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultRenamedUserOrder.Field {
		query = query.Order(DefaultRenamedUserOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *renameduserPager) orderExpr(query *UserQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultRenamedUserOrder.Field {
			b.Comma().Ident(DefaultRenamedUserOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to RenamedUser.
func (u *UserQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...RenamedUserPaginateOption,
) (*RenamedUserConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newRenamedUserPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if u, err = pager.applyFilter(u); err != nil {
		return nil, err
	}
	conn := &RenamedUserConnection{Edges: []*RenamedUserEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = u.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if u, err = pager.applyCursors(u, after, before); err != nil {
		return nil, err
	}
	if limit := paginateLimit(first, last); limit != 0 {
		u.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := u.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	u = pager.applyOrder(u)
	nodes, err := u.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// RenamedUserOrderField defines the ordering field of User.
type RenamedUserOrderField struct {
	// Value extracts the ordering value from the given User.
	Value    func(*RenamedUser) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) user.OrderOption
	toCursor func(*RenamedUser) Cursor
}

// RenamedUserOrder defines the ordering of User.
type RenamedUserOrder struct {
	Direction OrderDirection         `json:"direction"`
	Field     *RenamedUserOrderField `json:"field"`
}

// DefaultRenamedUserOrder is the default ordering of User.
var DefaultRenamedUserOrder = &RenamedUserOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &RenamedUserOrderField{
		Value: func(u *RenamedUser) (ent.Value, error) {
			return u.ID, nil
		},
		column: user.FieldID,
		toTerm: user.ByID,
		toCursor: func(u *RenamedUser) Cursor {
			return Cursor{ID: u.ID}
		},
	},
}

// ToEdge converts RenamedUser into RenamedUserEdge.
func (u *RenamedUser) ToEdge(order *RenamedUserOrder) *RenamedUserEdge {
	if order == nil {
		order = DefaultRenamedUserOrder
	}
	return &RenamedUserEdge{
		Node:   u,
		Cursor: order.Field.toCursor(u),
	}
}
