// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/bug/ent/unrenameduser"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UnrenamedUserCreate is the builder for creating a UnrenamedUser entity.
type UnrenamedUserCreate struct {
	config
	mutation *UnrenamedUserMutation
	hooks    []Hook
}

// SetAge sets the "age" field.
func (uuc *UnrenamedUserCreate) SetAge(i int) *UnrenamedUserCreate {
	uuc.mutation.SetAge(i)
	return uuc
}

// SetName sets the "name" field.
func (uuc *UnrenamedUserCreate) SetName(s string) *UnrenamedUserCreate {
	uuc.mutation.SetName(s)
	return uuc
}

// Mutation returns the UnrenamedUserMutation object of the builder.
func (uuc *UnrenamedUserCreate) Mutation() *UnrenamedUserMutation {
	return uuc.mutation
}

// Save creates the UnrenamedUser in the database.
func (uuc *UnrenamedUserCreate) Save(ctx context.Context) (*UnrenamedUser, error) {
	return withHooks(ctx, uuc.sqlSave, uuc.mutation, uuc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uuc *UnrenamedUserCreate) SaveX(ctx context.Context) *UnrenamedUser {
	v, err := uuc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uuc *UnrenamedUserCreate) Exec(ctx context.Context) error {
	_, err := uuc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuc *UnrenamedUserCreate) ExecX(ctx context.Context) {
	if err := uuc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uuc *UnrenamedUserCreate) check() error {
	if _, ok := uuc.mutation.Age(); !ok {
		return &ValidationError{Name: "age", err: errors.New(`ent: missing required field "UnrenamedUser.age"`)}
	}
	if _, ok := uuc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "UnrenamedUser.name"`)}
	}
	return nil
}

func (uuc *UnrenamedUserCreate) sqlSave(ctx context.Context) (*UnrenamedUser, error) {
	if err := uuc.check(); err != nil {
		return nil, err
	}
	_node, _spec := uuc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uuc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	uuc.mutation.id = &_node.ID
	uuc.mutation.done = true
	return _node, nil
}

func (uuc *UnrenamedUserCreate) createSpec() (*UnrenamedUser, *sqlgraph.CreateSpec) {
	var (
		_node = &UnrenamedUser{config: uuc.config}
		_spec = sqlgraph.NewCreateSpec(unrenameduser.Table, sqlgraph.NewFieldSpec(unrenameduser.FieldID, field.TypeInt))
	)
	if value, ok := uuc.mutation.Age(); ok {
		_spec.SetField(unrenameduser.FieldAge, field.TypeInt, value)
		_node.Age = value
	}
	if value, ok := uuc.mutation.Name(); ok {
		_spec.SetField(unrenameduser.FieldName, field.TypeString, value)
		_node.Name = value
	}
	return _node, _spec
}

// UnrenamedUserCreateBulk is the builder for creating many UnrenamedUser entities in bulk.
type UnrenamedUserCreateBulk struct {
	config
	builders []*UnrenamedUserCreate
}

// Save creates the UnrenamedUser entities in the database.
func (uucb *UnrenamedUserCreateBulk) Save(ctx context.Context) ([]*UnrenamedUser, error) {
	specs := make([]*sqlgraph.CreateSpec, len(uucb.builders))
	nodes := make([]*UnrenamedUser, len(uucb.builders))
	mutators := make([]Mutator, len(uucb.builders))
	for i := range uucb.builders {
		func(i int, root context.Context) {
			builder := uucb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UnrenamedUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uucb *UnrenamedUserCreateBulk) SaveX(ctx context.Context) []*UnrenamedUser {
	v, err := uucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uucb *UnrenamedUserCreateBulk) Exec(ctx context.Context) error {
	_, err := uucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uucb *UnrenamedUserCreateBulk) ExecX(ctx context.Context) {
	if err := uucb.Exec(ctx); err != nil {
		panic(err)
	}
}
