// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/bug/ent/predicate"
	"entgo.io/bug/ent/unrenameduser"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UnrenamedUserQuery is the builder for querying UnrenamedUser entities.
type UnrenamedUserQuery struct {
	config
	ctx        *QueryContext
	order      []unrenameduser.OrderOption
	inters     []Interceptor
	predicates []predicate.UnrenamedUser
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*UnrenamedUser) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UnrenamedUserQuery builder.
func (uuq *UnrenamedUserQuery) Where(ps ...predicate.UnrenamedUser) *UnrenamedUserQuery {
	uuq.predicates = append(uuq.predicates, ps...)
	return uuq
}

// Limit the number of records to be returned by this query.
func (uuq *UnrenamedUserQuery) Limit(limit int) *UnrenamedUserQuery {
	uuq.ctx.Limit = &limit
	return uuq
}

// Offset to start from.
func (uuq *UnrenamedUserQuery) Offset(offset int) *UnrenamedUserQuery {
	uuq.ctx.Offset = &offset
	return uuq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uuq *UnrenamedUserQuery) Unique(unique bool) *UnrenamedUserQuery {
	uuq.ctx.Unique = &unique
	return uuq
}

// Order specifies how the records should be ordered.
func (uuq *UnrenamedUserQuery) Order(o ...unrenameduser.OrderOption) *UnrenamedUserQuery {
	uuq.order = append(uuq.order, o...)
	return uuq
}

// First returns the first UnrenamedUser entity from the query.
// Returns a *NotFoundError when no UnrenamedUser was found.
func (uuq *UnrenamedUserQuery) First(ctx context.Context) (*UnrenamedUser, error) {
	nodes, err := uuq.Limit(1).All(setContextOp(ctx, uuq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{unrenameduser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uuq *UnrenamedUserQuery) FirstX(ctx context.Context) *UnrenamedUser {
	node, err := uuq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UnrenamedUser ID from the query.
// Returns a *NotFoundError when no UnrenamedUser ID was found.
func (uuq *UnrenamedUserQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uuq.Limit(1).IDs(setContextOp(ctx, uuq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{unrenameduser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uuq *UnrenamedUserQuery) FirstIDX(ctx context.Context) int {
	id, err := uuq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UnrenamedUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UnrenamedUser entity is found.
// Returns a *NotFoundError when no UnrenamedUser entities are found.
func (uuq *UnrenamedUserQuery) Only(ctx context.Context) (*UnrenamedUser, error) {
	nodes, err := uuq.Limit(2).All(setContextOp(ctx, uuq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{unrenameduser.Label}
	default:
		return nil, &NotSingularError{unrenameduser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uuq *UnrenamedUserQuery) OnlyX(ctx context.Context) *UnrenamedUser {
	node, err := uuq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UnrenamedUser ID in the query.
// Returns a *NotSingularError when more than one UnrenamedUser ID is found.
// Returns a *NotFoundError when no entities are found.
func (uuq *UnrenamedUserQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uuq.Limit(2).IDs(setContextOp(ctx, uuq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{unrenameduser.Label}
	default:
		err = &NotSingularError{unrenameduser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uuq *UnrenamedUserQuery) OnlyIDX(ctx context.Context) int {
	id, err := uuq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UnrenamedUsers.
func (uuq *UnrenamedUserQuery) All(ctx context.Context) ([]*UnrenamedUser, error) {
	ctx = setContextOp(ctx, uuq.ctx, "All")
	if err := uuq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UnrenamedUser, *UnrenamedUserQuery]()
	return withInterceptors[[]*UnrenamedUser](ctx, uuq, qr, uuq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uuq *UnrenamedUserQuery) AllX(ctx context.Context) []*UnrenamedUser {
	nodes, err := uuq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UnrenamedUser IDs.
func (uuq *UnrenamedUserQuery) IDs(ctx context.Context) (ids []int, err error) {
	if uuq.ctx.Unique == nil && uuq.path != nil {
		uuq.Unique(true)
	}
	ctx = setContextOp(ctx, uuq.ctx, "IDs")
	if err = uuq.Select(unrenameduser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uuq *UnrenamedUserQuery) IDsX(ctx context.Context) []int {
	ids, err := uuq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uuq *UnrenamedUserQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uuq.ctx, "Count")
	if err := uuq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uuq, querierCount[*UnrenamedUserQuery](), uuq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uuq *UnrenamedUserQuery) CountX(ctx context.Context) int {
	count, err := uuq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uuq *UnrenamedUserQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uuq.ctx, "Exist")
	switch _, err := uuq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uuq *UnrenamedUserQuery) ExistX(ctx context.Context) bool {
	exist, err := uuq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UnrenamedUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uuq *UnrenamedUserQuery) Clone() *UnrenamedUserQuery {
	if uuq == nil {
		return nil
	}
	return &UnrenamedUserQuery{
		config:     uuq.config,
		ctx:        uuq.ctx.Clone(),
		order:      append([]unrenameduser.OrderOption{}, uuq.order...),
		inters:     append([]Interceptor{}, uuq.inters...),
		predicates: append([]predicate.UnrenamedUser{}, uuq.predicates...),
		// clone intermediate query.
		sql:  uuq.sql.Clone(),
		path: uuq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Age int `json:"age,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UnrenamedUser.Query().
//		GroupBy(unrenameduser.FieldAge).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (uuq *UnrenamedUserQuery) GroupBy(field string, fields ...string) *UnrenamedUserGroupBy {
	uuq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UnrenamedUserGroupBy{build: uuq}
	grbuild.flds = &uuq.ctx.Fields
	grbuild.label = unrenameduser.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Age int `json:"age,omitempty"`
//	}
//
//	client.UnrenamedUser.Query().
//		Select(unrenameduser.FieldAge).
//		Scan(ctx, &v)
func (uuq *UnrenamedUserQuery) Select(fields ...string) *UnrenamedUserSelect {
	uuq.ctx.Fields = append(uuq.ctx.Fields, fields...)
	sbuild := &UnrenamedUserSelect{UnrenamedUserQuery: uuq}
	sbuild.label = unrenameduser.Label
	sbuild.flds, sbuild.scan = &uuq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UnrenamedUserSelect configured with the given aggregations.
func (uuq *UnrenamedUserQuery) Aggregate(fns ...AggregateFunc) *UnrenamedUserSelect {
	return uuq.Select().Aggregate(fns...)
}

func (uuq *UnrenamedUserQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uuq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uuq); err != nil {
				return err
			}
		}
	}
	for _, f := range uuq.ctx.Fields {
		if !unrenameduser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uuq.path != nil {
		prev, err := uuq.path(ctx)
		if err != nil {
			return err
		}
		uuq.sql = prev
	}
	return nil
}

func (uuq *UnrenamedUserQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UnrenamedUser, error) {
	var (
		nodes = []*UnrenamedUser{}
		_spec = uuq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UnrenamedUser).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UnrenamedUser{config: uuq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(uuq.modifiers) > 0 {
		_spec.Modifiers = uuq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uuq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	for i := range uuq.loadTotal {
		if err := uuq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (uuq *UnrenamedUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uuq.querySpec()
	if len(uuq.modifiers) > 0 {
		_spec.Modifiers = uuq.modifiers
	}
	_spec.Node.Columns = uuq.ctx.Fields
	if len(uuq.ctx.Fields) > 0 {
		_spec.Unique = uuq.ctx.Unique != nil && *uuq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, uuq.driver, _spec)
}

func (uuq *UnrenamedUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(unrenameduser.Table, unrenameduser.Columns, sqlgraph.NewFieldSpec(unrenameduser.FieldID, field.TypeInt))
	_spec.From = uuq.sql
	if unique := uuq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uuq.path != nil {
		_spec.Unique = true
	}
	if fields := uuq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, unrenameduser.FieldID)
		for i := range fields {
			if fields[i] != unrenameduser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uuq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uuq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uuq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uuq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uuq *UnrenamedUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uuq.driver.Dialect())
	t1 := builder.Table(unrenameduser.Table)
	columns := uuq.ctx.Fields
	if len(columns) == 0 {
		columns = unrenameduser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uuq.sql != nil {
		selector = uuq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uuq.ctx.Unique != nil && *uuq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range uuq.predicates {
		p(selector)
	}
	for _, p := range uuq.order {
		p(selector)
	}
	if offset := uuq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uuq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UnrenamedUserGroupBy is the group-by builder for UnrenamedUser entities.
type UnrenamedUserGroupBy struct {
	selector
	build *UnrenamedUserQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uugb *UnrenamedUserGroupBy) Aggregate(fns ...AggregateFunc) *UnrenamedUserGroupBy {
	uugb.fns = append(uugb.fns, fns...)
	return uugb
}

// Scan applies the selector query and scans the result into the given value.
func (uugb *UnrenamedUserGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uugb.build.ctx, "GroupBy")
	if err := uugb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UnrenamedUserQuery, *UnrenamedUserGroupBy](ctx, uugb.build, uugb, uugb.build.inters, v)
}

func (uugb *UnrenamedUserGroupBy) sqlScan(ctx context.Context, root *UnrenamedUserQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uugb.fns))
	for _, fn := range uugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uugb.flds)+len(uugb.fns))
		for _, f := range *uugb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uugb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uugb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UnrenamedUserSelect is the builder for selecting fields of UnrenamedUser entities.
type UnrenamedUserSelect struct {
	*UnrenamedUserQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uus *UnrenamedUserSelect) Aggregate(fns ...AggregateFunc) *UnrenamedUserSelect {
	uus.fns = append(uus.fns, fns...)
	return uus
}

// Scan applies the selector query and scans the result into the given value.
func (uus *UnrenamedUserSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uus.ctx, "Select")
	if err := uus.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UnrenamedUserQuery, *UnrenamedUserSelect](ctx, uus.UnrenamedUserQuery, uus, uus.inters, v)
}

func (uus *UnrenamedUserSelect) sqlScan(ctx context.Context, root *UnrenamedUserQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uus.fns))
	for _, fn := range uus.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uus.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
