// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/bug/ent/unrenameduser"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UnrenamedUser is the model entity for the UnrenamedUser schema.
type UnrenamedUser struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Age holds the value of the "age" field.
	Age int `json:"age,omitempty"`
	// Name holds the value of the "name" field.
	Name         string `json:"name,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UnrenamedUser) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case unrenameduser.FieldID, unrenameduser.FieldAge:
			values[i] = new(sql.NullInt64)
		case unrenameduser.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UnrenamedUser fields.
func (uu *UnrenamedUser) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case unrenameduser.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			uu.ID = int(value.Int64)
		case unrenameduser.FieldAge:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field age", values[i])
			} else if value.Valid {
				uu.Age = int(value.Int64)
			}
		case unrenameduser.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				uu.Name = value.String
			}
		default:
			uu.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UnrenamedUser.
// This includes values selected through modifiers, order, etc.
func (uu *UnrenamedUser) Value(name string) (ent.Value, error) {
	return uu.selectValues.Get(name)
}

// Update returns a builder for updating this UnrenamedUser.
// Note that you need to call UnrenamedUser.Unwrap() before calling this method if this UnrenamedUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (uu *UnrenamedUser) Update() *UnrenamedUserUpdateOne {
	return NewUnrenamedUserClient(uu.config).UpdateOne(uu)
}

// Unwrap unwraps the UnrenamedUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (uu *UnrenamedUser) Unwrap() *UnrenamedUser {
	_tx, ok := uu.config.driver.(*txDriver)
	if !ok {
		panic("ent: UnrenamedUser is not a transactional entity")
	}
	uu.config.driver = _tx.drv
	return uu
}

// String implements the fmt.Stringer.
func (uu *UnrenamedUser) String() string {
	var builder strings.Builder
	builder.WriteString("UnrenamedUser(")
	builder.WriteString(fmt.Sprintf("id=%v, ", uu.ID))
	builder.WriteString("age=")
	builder.WriteString(fmt.Sprintf("%v", uu.Age))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(uu.Name)
	builder.WriteByte(')')
	return builder.String()
}

// UnrenamedUsers is a parsable slice of UnrenamedUser.
type UnrenamedUsers []*UnrenamedUser
