// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// UnrenamedUser is the predicate function for unrenameduser builders.
type UnrenamedUser func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
